kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app.openshift.io/runtime: nodejs
spec:
  strategy:
    type: Rolling
    resources: {{ if .Values.resources }}
      requests:
        memory: {{ .Values.resources.deploy.requests.memory }}
        cpu: {{ .Values.resources.deploy.requests.cpu }}
      limits:
        memory: {{ .Values.resources.deploy.limits.memory }}
        cpu: {{ .Values.resources.deploy.limits.cpu }}
    {{ else }}{}{{end}}
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.deployment.name }}
        from:
          kind: ImageStreamTag
          namespace: {{ .Values.imageStream.namespace }}
          name: {{ .Values.imageStream.name }}:{{ .Values.imageStream.tag }}
    - type: ConfigChange
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  test: false
  selector:
    app: {{ .Values.deployment.name }}
    deploymentconfig: {{ .Values.deployment.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.name }}
        deploymentconfig: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: " "
          resources: {{ if .Values.resources }}
            requests:
              memory: {{ .Values.resources.pod.requests.memory }}
              cpu: {{ .Values.resources.pod.requests.cpu }}
            limits:
              memory: {{ .Values.resources.pod.limits.memory }}
              cpu: {{ .Values.resources.pod.limits.cpu }}
          {{ else }}{}{{end}}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
